# Generated by Django 6.0.4 on 2026-06-18 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('work_done', models.TextField()),
                ('workers_count', models.PositiveSmallIntegerField(default=0)),
                ('materials_used', models.TextField(blank=True, default='—')),
                ('equipment_used', models.TextField(blank=True, default='—')),
                ('problems', models.TextField(blank=True, default='Aucun')),
                ('solutions', models.TextField(blank=True, default='RAS')),
                ('weather', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('progress_today', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='projects.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='tasks.task')),
            ],
            options={
                'verbose_name': 'Rapport journalier',
                'verbose_name_plural': 'Rapports journaliers',
                'ordering': ['-report_date'],
            },
        ),
    ]
