# Generated by Django 6.0.4 on 2026-06-18 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=300)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('start_date', models.DateField()),
                ('expected_end_date', models.DateField()),
                ('real_end_date', models.DateField(blank=True, null=True)),
                ('initial_budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('planned', 'Planifié'), ('in_progress', 'En cours'), ('on_hold', 'En pause'), ('delayed', 'En retard'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-updated_at'],
            },
        ),
    ]
