# Generated by Django 6.0.4 on 2026-06-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SitePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='site_photos/%Y/%m/')),
                ('description', models.TextField(blank=True)),
                ('photo_type', models.CharField(choices=[('progress', 'Avancement'), ('problem', 'Problème'), ('material', 'Matériel'), ('security', 'Sécurité'), ('other', 'Autre')], default='other', max_length=20)),
                ('taken_at', models.DateTimeField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Photo de chantier',
                'verbose_name_plural': 'Photos de chantier',
                'ordering': ['-taken_at'],
            },
        ),
    ]
